Repository packed-hexagon/mini-project, pull requests merged in 2024-07, with the labels that each got.

#5 Refactor: ReservationEntity엔티티 수정(#1)
  src/main/java/com/group6/accommodation/domain/reservation/model/entity/ReservationEntity.java
Labels: refactoring

#4 Refactor: Accommodation 엔티티 수정(#1)
  src/main/java/com/group6/accommodation/domain/accommodation/converter/AccommodationConverter.java
  src/main/java/com/group6/accommodation/domain/accommodation/model/dto/AccommodationConditionRequestDto.java
  src/main/java/com/group6/accommodation/domain/accommodation/model/dto/AccommodationDetailResponseDto.java
  src/main/java/com/group6/accommodation/domain/accommodation/model/dto/AccommodationResponseDto.java
  src/main/java/com/group6/accommodation/domain/accommodation/model/entity/AccommodationEntity.java
  src/main/java/com/group6/accommodation/domain/accommodation/service/AccommodationApiService.java
  src/main/java/com/group6/accommodation/domain/accommodation/service/AccommodationService.java
Labels: refactoring

#7 Refactor: UserLikeEntity엔티티 수정(#1)
  src/main/java/com/group6/accommodation/AccommodationApplication.java
  src/main/java/com/group6/accommodation/domain/likes/model/entity/UserLikeEntity.java
  src/main/java/com/group6/accommodation/domain/review/model/entity/ReviewEntity.java
Labels: refactoring

#9 Refactor/room
  src/main/java/com/group6/accommodation/domain/reservation/service/ReserveService.java
  src/main/java/com/group6/accommodation/domain/room/converter/RoomConverter.java
  src/main/java/com/group6/accommodation/domain/room/model/dto/RoomDto.java
  src/main/java/com/group6/accommodation/domain/room/model/entity/RoomEntity.java
  src/main/java/com/group6/accommodation/domain/room/service/RoomApiService.java
  src/main/java/com/group6/accommodation/domain/room/service/RoomService.java
  src/test/java/com/group6/accommodation/domain/room/repository/RoomRepositoryTest.java
Labels: refactoring

#16 Refactor/#15 Build 오류 해결을 위한 메소드 임시 주석처리
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feat.yml
  .github/ISSUE_TEMPLATE/meeting.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  src/main/java/com/group6/accommodation/domain/accommodation/converter/AccommodationConverter.java
  src/main/java/com/group6/accommodation/domain/reservation/controller/ReserveController.java
  src/main/java/com/group6/accommodation/domain/reservation/converter/ReservationConverter.java
  src/main/java/com/group6/accommodation/domain/reservation/service/ReserveService.java
Labels: bug

#18 Fix : 에러 수정 (#15)
  src/main/java/com/group6/accommodation/AccommodationApplication.java
  src/main/java/com/group6/accommodation/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/group6/accommodation/domain/room/converter/RoomConverter.java
  src/main/java/com/group6/accommodation/domain/room/model/dto/RoomDto.java
  src/main/java/com/group6/accommodation/domain/room/model/entity/RoomEntity.java
  src/main/java/com/group6/accommodation/domain/room/repository/RoomRepository.java
  src/main/java/com/group6/accommodation/domain/room/service/RoomApiService.java
Labels: bug

#19 Refactor/#10
  src/main/java/com/group6/accommodation/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/group6/accommodation/domain/auth/repository/UserRepository.java
  src/main/java/com/group6/accommodation/domain/reservation/controller/ReservationController.java
  src/main/java/com/group6/accommodation/domain/reservation/converter/ReservationConverter.java
  src/main/java/com/group6/accommodation/domain/reservation/model/dto/PostReservationRequestDto.java
  src/main/java/com/group6/accommodation/domain/reservation/model/dto/ReservationResponseDto.java
  src/main/java/com/group6/accommodation/domain/reservation/model/entity/ReservationEntity.java
  src/main/java/com/group6/accommodation/domain/reservation/service/ReservationService.java
  src/main/java/com/group6/accommodation/domain/room/model/entity/RoomEntity.java
  src/main/java/com/group6/accommodation/domain/room/repository/RoomRepository.java
  src/main/java/com/group6/accommodation/global/exception/error/ReservationErrorCode.java
  src/test/java/com/group6/accommodation/domain/reservation/controller/ReservationControllerTest.java
  src/test/java/com/group6/accommodation/domain/reservation/service/ReservationServiceTest.java
  src/test/java/com/group6/accommodation/domain/reservation/service/ReserveServiceLockTest.java
Labels: refactoring

#23 Refactor/#20 모든 엔티티에 Timestamp 적용
  src/main/java/com/group6/accommodation/domain/accommodation/model/entity/AccommodationEntity.java
  src/main/java/com/group6/accommodation/domain/auth/model/entity/UserEntity.java
  src/main/java/com/group6/accommodation/domain/likes/model/entity/UserLikeEntity.java
  src/main/java/com/group6/accommodation/domain/reservation/model/entity/ReservationEntity.java
  src/main/java/com/group6/accommodation/domain/room/model/entity/RoomEntity.java
  src/main/java/com/group6/accommodation/global/model/entity/TimeStamp.java
Labels: refactoring

#22 Refactor/#12
  src/main/java/com/group6/accommodation/domain/accommodation/annotation/ValidArea.java
  src/main/java/com/group6/accommodation/domain/accommodation/annotation/ValidCategory.java
  src/main/java/com/group6/accommodation/domain/accommodation/annotation/validator/AreaValidator.java
  src/main/java/com/group6/accommodation/domain/accommodation/annotation/validator/CategoryValidator.java
  src/main/java/com/group6/accommodation/domain/accommodation/annotation/validator/StartBeforeEndAndNullableValidator.java
  src/main/java/com/group6/accommodation/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/group6/accommodation/domain/accommodation/model/dto/AccommodationConditionRequestDto.java
  src/main/java/com/group6/accommodation/domain/accommodation/model/enums/Area.java
  src/main/java/com/group6/accommodation/domain/accommodation/model/enums/Category.java
  src/main/java/com/group6/accommodation/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/group6/accommodation/domain/accommodation/service/AccommodationService.java
Labels: refactoring

#27 Refactor/#24
  src/main/java/com/group6/accommodation/domain/reservation/controller/ReservationController.java
  src/main/java/com/group6/accommodation/domain/reservation/model/dto/ReservationListItemDto.java
  src/main/java/com/group6/accommodation/domain/reservation/model/dto/ReservationRequestParamDto.java
  src/main/java/com/group6/accommodation/domain/reservation/model/entity/ReservationEntity.java
  src/main/java/com/group6/accommodation/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/group6/accommodation/domain/reservation/service/ReservationService.java
  src/main/java/com/group6/accommodation/global/model/dto/PagedDto.java
  src/test/java/com/group6/accommodation/domain/reservation/controller/ReservationControllerTest.java
  src/test/java/com/group6/accommodation/domain/reservation/service/ReservationServiceTest.java
Labels: refactoring

#29 Refactor: 피드백 기반 수정 (#14)
  src/main/java/com/group6/accommodation/domain/likes/repository/UserLikeRepository.java
  src/main/java/com/group6/accommodation/domain/likes/service/UserLikeService.java
Labels: refactoring

#32 Refactor/#28
  src/main/java/com/group6/accommodation/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/group6/accommodation/domain/reservation/controller/ReservationController.java
  src/main/java/com/group6/accommodation/domain/reservation/model/dto/ReservationResponseDto.java
  src/main/java/com/group6/accommodation/domain/reservation/model/entity/ReservationEntity.java
  src/main/java/com/group6/accommodation/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/group6/accommodation/domain/reservation/service/ReservationService.java
Labels: refactoring

#33 Refactor/#31 유저 레포지토리 관련 서비스 메소드 통합
  src/main/java/com/group6/accommodation/domain/auth/repository/UserRepository.java
  src/main/java/com/group6/accommodation/domain/auth/service/UserService.java
  src/main/java/com/group6/accommodation/domain/likes/service/UserLikeService.java
  src/main/java/com/group6/accommodation/global/exception/error/AuthErrorCode.java
  src/test/java/com/group6/accommodation/domain/auth/service/UserServiceTest.java
Labels: refactoring

#35 Feature/#34 방 예약 동시성 제어
  src/main/java/com/group6/accommodation/domain/room/repository/RoomRepository.java
Labels: enhancement

#37 Refactor/#25
  src/main/java/com/group6/accommodation/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/group6/accommodation/domain/accommodation/converter/AccommodationConverter.java
  src/main/java/com/group6/accommodation/domain/accommodation/model/dto/AccommodationConditionRequestDto.java
  src/main/java/com/group6/accommodation/domain/accommodation/model/dto/AccommodationDetailResponseDto.java
  src/main/java/com/group6/accommodation/domain/accommodation/model/dto/AccommodationResponseDto.java
  src/main/java/com/group6/accommodation/domain/accommodation/model/entity/AccommodationEntity.java
  src/main/java/com/group6/accommodation/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/group6/accommodation/domain/accommodation/service/AccommodationService.java
  src/main/java/com/group6/accommodation/domain/accommodation/service/command/AccommodationSearchCommand.java
  src/main/java/com/group6/accommodation/domain/accommodation/service/specification/AccommodationSpecification.java
  src/main/java/com/group6/accommodation/domain/likes/service/UserLikeService.java
  src/main/java/com/group6/accommodation/domain/room/repository/RoomRepository.java
Labels: refactoring

#39 Refactor/#36 refreshTokens 기능 헤더 관련 로직 서비스 분리
  src/main/java/com/group6/accommodation/domain/auth/controller/UserController.java
  src/main/java/com/group6/accommodation/domain/auth/service/UserService.java
  src/main/java/com/group6/accommodation/global/util/CookieUtil.java
Labels: refactoring

#42 Feature/#34 분산 락 적용
  src/main/java/com/group6/accommodation/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/group6/accommodation/domain/reservation/model/entity/ReservationEntity.java
  src/main/java/com/group6/accommodation/domain/reservation/service/ReservationService.java
  src/main/java/com/group6/accommodation/domain/room/repository/RoomRepository.java
  src/main/java/com/group6/accommodation/global/annotation/RedissonLock.java
  src/main/java/com/group6/accommodation/global/annotation/aspect/AopForTransaction.java
  src/main/java/com/group6/accommodation/global/annotation/aspect/ElParser.java
  src/main/java/com/group6/accommodation/global/annotation/aspect/RedissonLockAspect.java
  src/main/java/com/group6/accommodation/global/redis/config/RedisConfig.java
Labels: refactoring
